### ISSUE TITLE
Create a proper unit test out of test.py

### ISSUE THREAD

**Issue by JohnGiorgi** [PathwayCommons/pathway-abstract-classifier#10]
Create a proper unit test out of `test.py`. The steps would be

- create a new directory, `tests` and place a empty `__init__.py` file under it.
- move `test.py` under `tests`, rename it to something more informative (`test_model.py`)
- re-write the function as a unit test, this basically means renaming it (e.g. `test_can_load_and_predict_model`)
- run the test with `pytest`. We will have to add this as a dependency. My vote would be to create a new file, `dev-requirements.txt` and put it there, following https://github.com/allenai/allennlp/blob/main/dev-requirements.txt
- Optionally but highly encouraged: set up a simple `ci.yml` to run this test on every PR.

**Comment by Steven-Palayew** [comment]
Done a good chunk of this now, but regarding point 4, are there any other dev-requirements we want? Or are we better off just saying to `pip install pytest` in readme?

**Comment by JohnGiorgi** [comment]
Yeah there's lots, ideally we would set up static code analysis tools like `flake8`, `black` and `mypy`. Lets just start with `pytest` in `dev-requirements.txt` though

**Comment by JohnGiorgi** [comment]
Did you open a PR for this? I see some of the changes merged directly to `main`? In general, we want to avoid committing to main. The general workflow would be: identify a problem or feature and open an issue --> open a PR and link it to the issue (you can do this by writing "Closes #issue-number") --> Get feedback and merge once everyone is happy

**Comment by Steven-Palayew** [comment]
My bad sorry. I just followed what you said to do word for word, so wasn't sure if this was necessary, but completely understand if you want to be more conservative in terms of double checking changes I make.

**Comment by JohnGiorgi** [comment]
No worries! This is more a coaching thing and about getting into good SWE habits :)
