### ISSUE TITLE
Name of Repo 

### ISSUE THREAD

**Issue by Steven-Palayew** [PathwayCommons/pathway-abstract-classifier#21]
Right now repo is called abstract classifier and description is set accordingly, but we are now also using titles. Need to choose a name that accounts for this.

**Comment by JohnGiorgi** [comment]
I don't think the repo really needs a name change, it's okay that we are using titles. Lots of NLP application only mention the abstract when they usually mean title + abstract.

If we do change it will have to make sure we don't break any links or URLs

**Comment by jvwong** [comment]
Biofabstract :)
